### ISSUE TITLE
[FIX]: remove toBeInTheDocument error in all test files

### ISSUE THREAD

**Issue by OlgaYasn** [ekino/v6y#35]
### 🐛 Description
All the test files containing `toBeInTheDocument()` have errors : "La propriété 'toBeInTheDocument' n'existe pas sur le type 'Assertion<HTMLElement>'"

### 🔍 Steps to Reproduce
1. Go to VitalityLighthouseReportsCategoryGrouper-test.tsx
2. Scroll down to the bottom of the page
3. See error

### ✅ Expected Behavior
The tests files should not contain any error. 

### ❌ Actual Behavior
An error is present everywhere where "toBeInTheDocument()" is used. 

### 📸 Screenshots
<img width="657" alt="Capture d’écran 2024-11-22 à 09 56 53" src="https://github.com/user-attachments/assets/94870284-945e-4cf7-a29a-f5a7171aaa85">

### 💻 Environment
- OS: [e.g., Windows, macOS, Linux]
- Browser: [e.g., Chrome, Safari]
- Version: [e.g., 22]
- Vitality v6y Version: [e.g., 1.0.0]

**Comment by OlgaYasn** [comment]
Starting point : 
If we add `@testing-library/jest-dom` just to one of the test files, all the error messages disappear. 
If `vitest.setup.ts` file is opened in IDE, the error messages automatically disappear. 


Tried methods : 
- Adding `@testing-library/jest-dom/vitest` in types array in tsconfig.json file
- Upgarde `@testing-library/jest-dom` to the latest version
- Add `@vitest/expect` as a new dependency
- Create `.npmrc` file with public-hoist-pattern[]=@types/*

**Comment by helabenkhalfallah** [comment]
Fixed!
