### ISSUE TITLE
[BUG]: correct createUrlQueryParam function name

### ISSUE THREAD

**Issue by OlgaYasn** [ekino/v6y#44]
### 🐛 Description
There is a spelling error in creatUrlQueryParam -> it should be createUrlQueryParam

### ❌ Actual Behavior
A clear and concise description of what actually happened.

### 💻 Environment
- OS: [e.g., Windows, macOS, Linux]
- Browser: [e.g., Chrome, Safari]
- Version: [e.g., 22]
- Vitality v6y Version: [e.g., 1.0.0]

### 🔗 Relevant Links (if any)
Add links to any relevant issues, discussions, or tickets.

**Comment by helabenkhalfallah** [comment]
DONE.
